// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using QuantityMeasurementAppRepositoryLayer.Data;

#nullable disable

namespace QuantityMeasurementAppRepositoryLayer.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("QuantityMeasurementAppModelLayer.Entity.QuantityMeasurementEntity", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                b.Property<string>("Category").IsRequired().HasColumnType("text");
                b.Property<string>("Operation").IsRequired().HasColumnType("text");
                b.Property<double>("Result").HasColumnType("double precision");
                b.Property<string>("Unit1").IsRequired().HasColumnType("text");
                b.Property<string>("Unit2").IsRequired().HasColumnType("text");
                b.Property<int>("UserId").HasColumnType("integer");
                b.Property<double>("Value1").HasColumnType("double precision");
                b.Property<double>("Value2").HasColumnType("double precision");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("Quantity");
            });

            modelBuilder.Entity("QuantityMeasurementAppModelLayer.Entity.UserEntity", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Email").IsRequired().HasColumnType("text");
                b.Property<string>("Password").IsRequired().HasColumnType("text");
                b.Property<string>("Phone").IsRequired().HasColumnType("text");
                b.Property<string>("UserName").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.ToTable("User");
            });

            modelBuilder.Entity("QuantityMeasurementAppModelLayer.Entity.QuantityMeasurementEntity", b =>
            {
                b.HasOne("QuantityMeasurementAppModelLayer.Entity.UserEntity", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
